#!/usr/bin/env bash
# ============================
# Logit Help Function
# ============================
LOGIT_HELP() {
    printf "${BOLD_TEXT}${CYAN_TEXT}Usage:${RESET_TEXT}\n"
    printf "  logit help     # Show usage and environment variable info\n"
    printf "  logit update   # Checks for newer versions, use with \-y\ for non-interactive update\n"
    printf "  logit version  # Show current Logit version\n"
    printf "\n"
    printf "  logit <LEVEL> \"Your message here\"\n"
    printf "\n"
    printf "${YELLOW_TEXT}Usage Examples:${RESET_TEXT}\n"
    printf "  logit INFO \"This is an informational message.\"\n"
    printf "  logit WARN \"This is a warning.\"\n"
    printf "  logit ERROR \"Something went wrong.\"\n"
    printf "  logit SUCCESS \"Task completed successfully.\"\n"
    printf "  logit DEBUG \"This is a debug message.\"\n"
    printf "\n"
    printf "${GREEN_TEXT}Inside script Environment Variables (export):${RESET_TEXT}\n"
    printf "  LOG_NAME:           Name of the log file | default: \$(basename \"\$0\" .sh)\n"
    printf "  PARENT_DIR:         Path to the parent dir | default: \$(basename \"\$(dirname "\$0\"\)")\n"
    printf "  LOG_FILE:           Path to the log file | default: \$PARENT_DIR/logs/\${LOG_NAME}.log\n"
    printf "  ERROR_LOG_FILE:     Path to the error log file | default: \$PARENT_DIR/logs/errors_\${LOG_NAME}.log\n"
    printf "  LOG_SIZE:           Maximum size of log file before rotating in MB | default: 3\n"
    printf "  MAX_LOG_FILES:      Number of rotated log files to keep | default: 3\n"
    printf "  SHOW_MESSAGE:       Set to \"true\" to also show logs to user (stdout) | default: \\\"true\\\"\n"
    printf "  HIDE_INFO:          Set to \"true\" with SHOW_MESSAGE to hide INFO messages from stdout | default: \\\"true\\\"\n"
    printf "  DEBUG_MODE:         Set to \\\"true\\\" to activate DEBUG mode which will log all commands | default: \\\"false\\\"\n"
    printf "  LOGIT_DATE_FORMAT:  Allows customizable timestamp format | default: %%Y-%%m-%%d %%H:%%M:%%S.%%3N\n"
    printf "\n"
    printf "${YELLOW_TEXT}Usage Examples:${RESET_TEXT}\n"
    printf "  export LOG_NAME=\"AwesomeScript\"\n"
    printf "  export PARENT_DIR=\"\AwesomeScript\"\n"
    printf "  export LOG_FILE=\"\home\AwesomeScript\Script.log\"\n"
    printf "  export ERROR_LOG_FILE=\"\home\AwesomeScript\error.log\"\n"
    printf "\n"
    printf "  export LOG_SIZE=\"5\"\n"
    printf "  export MAX_LOG_FILES=\"10\"\n"
    printf "  export SHOW_MESSAGE=\"true\"\n"
    printf "  export HIDE_INFO=\"false\"\n"
    printf "  export DEBUG_MODE=\"true\"\n"
    printf "  export LOGIT_DATE_FORMAT=\"%%d-%%m-%%Y %%H:%%M:%%S\"\n"
    printf "\n"
    printf 'source \\path\\to\\logit.sh\n'
}
